name: 测试

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/打包.yml'
      - 'ESP/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/打包.yml'
      - 'ESP/**'

jobs:
  build:
    strategy:
      matrix:
        type: [Yours-UEFI]

    name: 打包 ${{ matrix.type }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 归档 ${{ matrix.type }}
      run: |
        sudo bash ./git.sh
        ls -l
        cd ESP
        ls -l
        cd EFI
        ls -l
        cd Yours
        ls -l
        sudo rm -r ./ESP/EFI/Yours/docs
    - name: 上传到此处
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.type }}
        path: ESP
