name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/打包.yml'
      - 'ESP/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/打包.yml'
      - 'ESP/**'

jobs:
  build:
    strategy:
      matrix:
        type: [Yours-UEFI]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 归档 ${{ matrix.type }}
      run: |
        sudo rm -r ./ESP/EFI/Yours/docs
    - name: 上传到此处
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.type }}
        path: ESP
